### ISSUE TITLE
Why MMLU score of Crystalcoder（~50） is so mush higher than Amber (~30)?

### ISSUE THREAD

**Issue by BitVoyage** [LLM360/crystalcoder-train#1]
The diff I obeserved is:
1. Crystalcoder Use SlimPajama as Non-Code Corpus
2. More code ratio in phrase 2

Could you provide more insights?

**Comment by aurickq** [comment]
CrystalCoder has higher scores overall due to using a cleaner dataset (SlimPajama) and more careful tuning (muP).

As for why MMLU in particular has such a big gap:

- There is evidence that including code in pretraining data improves MMLU. We also observed that MMLU improves much more rapidly during CrystalCoder's second stage when code data is added. See https://wandb.ai/llm360/CrystalCoder.
- Amber had a training precision bug mentioned in our paper that disproportionately impacted its MMLU score.

**Comment by BitVoyage** [comment]
Thank you for your explanation！
